/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Thanh Phuc
 */
public class Admin_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Frame
     */
    public Admin_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_Qlnv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_thongke = new javax.swing.JButton();
        btn_qlSach = new javax.swing.JButton();
        btn_qltk = new javax.swing.JButton();
        btn_dangxuat = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        btn_kho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        btn_Qlnv.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_Qlnv.setText("Quản lí nhân viên");
        btn_Qlnv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Qlnv.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Qlnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QlnvActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Qlnv);
<<<<<<< HEAD
        btn_Qlnv.setBounds(20, 80, 180, 140);
=======
        btn_Qlnv.setBounds(20, 80, 180, 31);
>>>>>>> 86fed4738ecf742be1b678a0c13b51baef411d6a

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Phần mềm quản lý cửa hàng bán sách");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 20, 580, 42);

        btn_thongke.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_thongke.setText("Thống kê doanh thu");
        btn_thongke.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_thongke.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongkeActionPerformed(evt);
            }
        });
        jPanel2.add(btn_thongke);
        btn_thongke.setBounds(470, 80, 191, 130);

        btn_qlSach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_qlSach.setText("Quản lý sách");
        btn_qlSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_qlSach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_qlSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlSachActionPerformed(evt);
            }
        });
        jPanel2.add(btn_qlSach);
        btn_qlSach.setBounds(20, 250, 180, 130);

        btn_qltk.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_qltk.setText("Quản lý tài khoản");
        btn_qltk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_qltk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_qltk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qltkActionPerformed(evt);
            }
        });
        jPanel2.add(btn_qltk);
        btn_qltk.setBounds(250, 81, 173, 130);

        btn_dangxuat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_dangxuat.setText("Đăng xuất");
        btn_dangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangxuatActionPerformed(evt);
            }
        });
        jPanel2.add(btn_dangxuat);
        btn_dangxuat.setBounds(20, 410, 180, 130);

        btn_thoat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_thoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        jPanel2.add(btn_thoat);
<<<<<<< HEAD
        btn_thoat.setBounds(240, 410, 180, 130);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 480);
=======
        btn_thoat.setBounds(480, 270, 180, 130);

        btn_kho.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_kho.setText("Quản lí phiếu nhập");
        btn_kho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_kho);
        btn_kho.setBounds(710, 80, 200, 130);
>>>>>>> 86fed4738ecf742be1b678a0c13b51baef411d6a

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_QlnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QlnvActionPerformed
        QLNV_Frame qlnv = new QLNV_Frame();
        qlnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_QlnvActionPerformed

    private void btn_qltkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qltkActionPerformed
        QLTK_Frame qltk = new QLTK_Frame();
        qltk.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_qltkActionPerformed

    private void btn_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongkeActionPerformed
        ThongKeDoanhThu_Frame thongKe = new ThongKeDoanhThu_Frame();
        thongKe.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_thongkeActionPerformed

    private void btn_qlSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlSachActionPerformed
        QLSach_Frame qlSach = new QLSach_Frame();
        qlSach.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_qlSachActionPerformed

    private void btn_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangxuatActionPerformed
        Login_Frame login = new Login_Frame();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_dangxuatActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_khoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khoActionPerformed
        QLKho_Frame kho=new QLKho_Frame();
        kho.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_khoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Qlnv;
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JButton btn_kho;
    private javax.swing.JButton btn_qlSach;
    private javax.swing.JButton btn_qltk;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_thongke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
