/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Thanh Phuc
 */
public class User_Frame extends javax.swing.JFrame {

    /**
     * Creates new form User_Frame
     */
    public User_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_banHang = new javax.swing.JButton();
        btn_capNhatDonHang = new javax.swing.JButton();
        btn_DangXuat = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Phần mềm quản lý cửa hàng bán sách");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 20, 590, 42);

        btn_banHang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_banHang.setIcon(new javax.swing.ImageIcon("D:\\Java\\QuanLyBanHang\\img\\dollar-icon.png")); // NOI18N
        btn_banHang.setText("Bán hàng");
        btn_banHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_banHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_banHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_banHangActionPerformed(evt);
            }
        });
        jPanel2.add(btn_banHang);
        btn_banHang.setBounds(80, 90, 200, 140);

        btn_capNhatDonHang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_capNhatDonHang.setIcon(new javax.swing.ImageIcon("D:\\Java\\QuanLyBanHang\\img\\Cart-icon.png")); // NOI18N
        btn_capNhatDonHang.setText("Cập nhật đơn hàng");
        btn_capNhatDonHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_capNhatDonHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_capNhatDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatDonHangActionPerformed(evt);
            }
        });
        jPanel2.add(btn_capNhatDonHang);
        btn_capNhatDonHang.setBounds(403, 90, 210, 140);

        btn_DangXuat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_DangXuat.setIcon(new javax.swing.ImageIcon("D:\\Java\\QuanLyBanHang\\img\\Other-Power-Log-Off-Metro-icon.png")); // NOI18N
        btn_DangXuat.setText("Đăng xuất");
        btn_DangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_DangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangXuatActionPerformed(evt);
            }
        });
        jPanel2.add(btn_DangXuat);
        btn_DangXuat.setBounds(80, 280, 200, 131);

        btn_thoat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_thoat.setIcon(new javax.swing.ImageIcon("D:\\Java\\QuanLyBanHang\\img\\blue-cross-icon.png")); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.setToolTipText("");
        btn_thoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_thoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        jPanel2.add(btn_thoat);
        btn_thoat.setBounds(400, 280, 210, 131);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Java\\QuanLyBanHang\\img\\1 (1).gif")); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 1, 740, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_banHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_banHangActionPerformed
        BanHang_Frame banhang = new BanHang_Frame();
        banhang.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_banHangActionPerformed

    private void btn_capNhatDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatDonHangActionPerformed
        CapNhatDonHang_Frame capNhat = new CapNhatDonHang_Frame();
        capNhat.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_capNhatDonHangActionPerformed

    private void btn_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangXuatActionPerformed
        Login_Frame login = new Login_Frame();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_DangXuatActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_thoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangXuat;
    private javax.swing.JButton btn_banHang;
    private javax.swing.JButton btn_capNhatDonHang;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
